---
- name: Creating CUPS tmp location {{ cups_tmp_location }}
  file:
    path: "{{cups_tmp_location}}"
    recurse: yes
    state: directory

- name: Creating {{ cups_ppd_shared_location }}
  file:
    path: "{{cups_ppd_shared_location}}"
    recurse: yes
    state: directory

# If the output is none or the command failed to find "install ok installed" then it means the package wasn't installed beforehand
- name: Check and register if expect related packages are already installed.
  command: dpkg -s {{item}} | grep 'install ok installed'
  register: cups_expect_pkgs_already_installed
  with_items:
    - "{{cups_expect_pkgs}}"
  changed_when: False
  failed_when: False

- name: Ensure expect related packages are installed to guide us through CUPS installation.
  apt: name={{ item }} state=present
  with_items:
    - "{{cups_expect_pkgs}}"
